FROM python:3.10-slim-buster

# Inside the container
# Make a new folder inside the container
WORKDIR /backend-flask

# Outside the container -> Inside the container
# This contains the libraries we want to install to run the app
COPY requirements.txt requirements.txt

# Inside the container
# Install python libraries used for the app
RUN pip3 install -r requirements.txt

# Outside the container -> Inside the container
# . Means everything
# First period . - /backend-flask (outside container)
# Second period . -/ backend-flask (inside container)
COPY . .

# Set environment variables
# Inside the container and will remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}

# CMD (Command)
# Python3", "-m" (modules) , "flask", "run", "--host=0.0.0.0" (everything address), "--port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]